@echo off
echo [1/4] Running UBVM Boot Sequence...
python "%~dp0boot.py"
echo [2/4] Starting Network Daemon (Port 8080)...
start "UBVM Network Node" python "%~dp0network_daemon.py" 8080
echo [3/4] Starting Scheduler (Cron + Event Bus)...
start "UBVM Scheduler" python "%~dp0scheduler_daemon.py"
echo [4/4] Launching Live Terminal Dashboard...
start "UBVM Display" "%~dp0clients\display.bat"
echo UBVM is now fully operational!