package com.giblets.roadwatch

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Environment
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object ExportManager {

    fun exportKml(context: Context, events: List<RoadEvent>): File? {
        if (events.isEmpty()) return null
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.UK)
        val filename = "roadwatch_${sdf.format(Date())}.kml"

        val sb = StringBuilder()
        sb.appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
        sb.appendLine("""<kml xmlns="http://www.opengis.net/kml/2.2">""")
        sb.appendLine("<Document>")
        sb.appendLine("<n>RoadWatch Export ${sdf.format(Date())}</n>")
        sb.appendLine("<description>Road quality data from RoadWatch by Giblets Creations</description>")

        mapOf(
            "pothole" to "#FF2020",
            "bump"    to "#FF8800",
            "rough"   to "#FFCC00",
            "smooth"  to "#00CC44"
        ).forEach { (name, colour) ->
            sb.appendLine("""<Style id="$name">
                <IconStyle>
                    <color>ff${colour.removePrefix("#").let {
                        it.substring(4,6)+it.substring(2,4)+it.substring(0,2)
                    }}</color>
                    <scale>${if (name == "pothole") "1.4" else "1.0"}</scale>
                </IconStyle>
            </Style>""")
        }

        events.forEach { sb.appendLine(it.toKmlPlacemark()) }
        sb.appendLine("</Document>")
        sb.appendLine("</kml>")

        return writeFile(context, filename, sb.toString())
    }

    fun exportGpx(context: Context, events: List<RoadEvent>): File? {
        if (events.isEmpty()) return null
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.UK)
        val filename = "roadwatch_${sdf.format(Date())}.gpx"

        val timeSdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.UK).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }

        val sb = StringBuilder()
        sb.appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
        sb.appendLine("""<gpx version="1.1" creator="RoadWatch by Giblets Creations"
  xmlns="http://www.topografix.com/GPX/1/1">""")
        sb.appendLine("<metadata>")
        sb.appendLine("  <n>RoadWatch ${sdf.format(Date())}</n>")
        sb.appendLine("  <desc>${events.size} road events recorded</desc>")
        sb.appendLine("  <time>${timeSdf.format(Date())}</time>")
        sb.appendLine("</metadata>")
        events.forEach { sb.appendLine(it.toGpxWpt()) }
        sb.appendLine("</gpx>")

        return writeFile(context, filename, sb.toString())
    }

    fun exportCouncilReport(context: Context, events: List<RoadEvent>): File? {
        if (events.isEmpty()) return null
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.UK)
        val dateSdf = SimpleDateFormat("dd MMM yyyy HH:mm", Locale.UK)
        val filename = "roadwatch_report_${sdf.format(Date())}.txt"

        val potholes = events.filter { it.type == EventType.POTHOLE }
        val bumps    = events.filter { it.type == EventType.BUMP }
        val rough    = events.filter { it.type == EventType.ROUGH }

        val sb = StringBuilder()
        sb.appendLine("=".repeat(60))
        sb.appendLine("ROADWATCH — ROAD CONDITION REPORT")
        sb.appendLine("Generated by RoadWatch | Giblets Creations")
        sb.appendLine("Date: ${dateSdf.format(Date())}")
        sb.appendLine("=".repeat(60))
        sb.appendLine()
        sb.appendLine("SUMMARY")
        sb.appendLine("-".repeat(40))
        sb.appendLine("Total events recorded : ${events.size}")
        sb.appendLine("Potholes detected     : ${potholes.size}")
        sb.appendLine("Speed bumps detected  : ${bumps.size}")
        sb.appendLine("Rough surface areas   : ${rough.size}")
        sb.appendLine()

        if (potholes.isNotEmpty()) {
            sb.appendLine("POTHOLE LOCATIONS")
            sb.appendLine("-".repeat(40))
            sb.appendLine()
            potholes.sortedByDescending { it.severity }.forEach { e ->
                sb.appendLine("  Severity  : ${"★".repeat(e.severity)}${"☆".repeat(5 - e.severity)} (${e.severity}/5)")
                sb.appendLine("  Location  : ${e.lat}, ${e.lon}")
                sb.appendLine("  Maps Link : https://maps.google.com/?q=${e.lat},${e.lon}")
                sb.appendLine("  Peak G    : ${"%.2f".format(e.peakG)}G")
                sb.appendLine("  Speed     : ${"%.0f".format(e.speedKmh)} km/h")
                sb.appendLine("  Detected  : ${dateSdf.format(Date(e.timestamp))}")
                sb.appendLine()
            }
        }

        if (rough.isNotEmpty()) {
            sb.appendLine("ROUGH SURFACE AREAS")
            sb.appendLine("-".repeat(40))
            rough.forEach { e ->
                sb.appendLine("  ${e.lat}, ${e.lon} — https://maps.google.com/?q=${e.lat},${e.lon}")
            }
            sb.appendLine()
        }

        sb.appendLine("=".repeat(60))
        sb.appendLine("Generated automatically by RoadWatch.")
        sb.appendLine("UK Highways Act 1980 — councils have statutory duty to maintain safe roads.")
        sb.appendLine("=".repeat(60))

        return writeFile(context, filename, sb.toString())
    }

    private fun writeFile(context: Context, filename: String, content: String): File? {
        return try {
            val dir = File(context.getExternalFilesDir(
                Environment.DIRECTORY_DOCUMENTS), "RoadWatch").also { it.mkdirs() }
            val file = File(dir, filename)
            file.writeText(content)
            file
        } catch (e: Exception) { null }
    }

    fun shareFile(context: Context, file: File) {
        val uri = Uri.fromFile(file)
        val intent = Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, getMimeType(file))
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(Intent.createChooser(intent, "Open with").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }

    private fun getMimeType(file: File) = when (file.extension.lowercase()) {
        "kml" -> "application/vnd.google-earth.kml+xml"
        "gpx" -> "application/gpx+xml"
        else  -> "text/plain"
    }
}
