github.com:
    users:
        JamesTheGiblet:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: JamesTheGiblet
